
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Boy
 */
public class Ögretmen extends javax.swing.JFrame {

    /**
     * Creates new form Ögretmen
     */
    public Ögretmen() {
        initComponents();
        tabloGüncelle();
    }

    public void tabloGüncelle() {
        Connection dbconn = VeriBaglanti.baglanti();

        int q;
        int i;
        try {
            PreparedStatement st = (PreparedStatement) dbconn.prepareStatement("select * from ögrenci");
            ResultSet res = st.executeQuery();
            ResultSetMetaData StData = (ResultSetMetaData) res.getMetaData();

            q = StData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) tablo.getModel();
            RecordTable.setRowCount(0);

            while (res.next()) {

                Vector columnData = new Vector();
                for (i = 1; i < q; i++) {
                    columnData.add(res.getString("id"));
                    columnData.add(res.getString("adi_soyadi"));
                    columnData.add(res.getString("karnenotu"));
                    columnData.add(res.getString("kullanici_adi"));
                    columnData.add(res.getString("kullanici_sifre"));
                    columnData.add(res.getString("email"));

                }
                RecordTable.addRow(columnData);
            }

        } catch (Exception ex) {
            Logger.getLogger(Ögrenci.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        adi_soyadi = new javax.swing.JTextField();
        kullanici_adi = new javax.swing.JTextField();
        karnenotu = new javax.swing.JTextField();
        kullanici_sifre = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Adı Soyadı", "Karne Notu", "Kullanıcı Adı", "Şifresi", "E-Mail"
            }
        ));
        jScrollPane1.setViewportView(tablo);

        jButton1.setText("EKLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GÜNCELLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SİL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("GERİ DÖN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("AD SOYAD :");

        jLabel2.setText("KARNE NOTU :");

        jLabel3.setText("KULLANICI ADI :");

        jLabel4.setText("ŞİFRESİ :");

        jLabel5.setText("EMAİL:");

        jLabel7.setText("ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adi_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(karnenotu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullanici_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adi_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(karnenotu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullanici_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kullanici_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String adsoyad = adi_soyadi.getText();
        String not = karnenotu.getText();
        String kulad = kullanici_adi.getText();
        String kulsif = kullanici_sifre.getText();
        String mail = email.getText();

        if (adsoyad.isEmpty() || kulad.isEmpty() || kulsif.isEmpty() || mail.isEmpty() || not.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tüm alanları doldurun !", "Hata", JOptionPane.ERROR_MESSAGE);
        } else {
            KayitEt(adsoyad, kulad, kulsif, mail, not);
            tabloGüncelle();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String i = id.getText();
        String adsoyad = adi_soyadi.getText();
        String not = karnenotu.getText();
        String kulad = kullanici_adi.getText();
        String kulsif = kullanici_sifre.getText();
        String mail = email.getText();

        if (i.isEmpty() || adsoyad.isEmpty() || not.isEmpty() || kulad.isEmpty() || kulsif.isEmpty() || mail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tüm alanları doldurun !", "Hata", JOptionPane.ERROR_MESSAGE);
        } else {
            Güncelle(i, adsoyad, not, kulad, kulsif, mail);
            tabloGüncelle();
        }

        tabloGüncelle();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String i = id.getText();

        if (i.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tüm alanları doldurun !", "Hata", JOptionPane.ERROR_MESSAGE);
        } else {
            Sil(i);
            tabloGüncelle();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminGiris ad = new AdminGiris();
        ad.setVisible(true);
        ad.setTitle("Öğretmen Giriş");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ögretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ögretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ögretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ögretmen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ögretmen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adi_soyadi;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField karnenotu;
    private javax.swing.JTextField kullanici_adi;
    private javax.swing.JTextField kullanici_sifre;
    private javax.swing.JTable tablo;
    // End of variables declaration//GEN-END:variables

    private void KayitEt(String adsoyad, String kulad, String kulsif, String mail, String not) {
        Connection dbconn = VeriBaglanti.baglanti();
        if (dbconn != null) {
            try {
                PreparedStatement st = (PreparedStatement) dbconn.prepareStatement("INSERT INTO ögrenci(adi_soyadi,kullanici_adi,kullanici_sifre,email,karnenotu) VALUES(?,?,?,?,?)");

                st.setString(1, adsoyad);
                st.setString(2, kulad);
                st.setString(3, kulsif);
                st.setString(4, mail);
                st.setString(5, not);

                int res = st.executeUpdate();

                JOptionPane.showMessageDialog(this, "Kullanıcı kaydı yapıldı.", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

                id.setText("");
                adi_soyadi.setText("");
                kullanici_adi.setText("");
                email.setText("");
                kullanici_adi.setText("");
                kullanici_sifre.setText("");
                karnenotu.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(Kayit.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("Bağlantı ulaşılabilir değil !");
        }
    }

    private void Güncelle(String i, String adsoyad, String not, String kulad, String kulsif, String mail) {
        Connection dbconn = VeriBaglanti.baglanti();
        if (dbconn != null) {
            try {
                PreparedStatement st = (PreparedStatement) dbconn.prepareStatement("UPDATE ögrenci set adi_soyadi=?,kullanici_adi=?,kullanici_sifre=?,email=?,karnenotu=? where id=? ");

                st.setString(1, adsoyad);
                st.setString(2, kulad);
                st.setString(3, kulsif);
                st.setString(4, mail);
                st.setString(5, not);
                st.setString(6, i);

                int res = st.executeUpdate();

                JOptionPane.showMessageDialog(this, "Güncelleme yapıldı.", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

                id.setText("");
                adi_soyadi.setText("");
                kullanici_adi.setText("");
                email.setText("");
                kullanici_adi.setText("");
                kullanici_sifre.setText("");
                karnenotu.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(Kayit.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("Bağlantı ulaşılabilir değil !");
        }
    }

    private void Sil(String i) {
         Connection dbconn = VeriBaglanti.baglanti();
        if (dbconn != null) {
            try {
                PreparedStatement st = (PreparedStatement) dbconn.prepareStatement("delete from ögrenci where id=?");

                st.setString(1, i);
                

                int res = st.executeUpdate();

                JOptionPane.showMessageDialog(this, "Kullanıcı silindi.", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

                id.setText("");
                adi_soyadi.setText("");
                kullanici_adi.setText("");
                email.setText("");
                kullanici_adi.setText("");
                kullanici_sifre.setText("");
                karnenotu.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(Kayit.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("Bağlantı ulaşılabilir değil !");
        }
    }
}
